# Introduction to NumPy

In [2]:
import numpy as np

In [2]:
x = np.array([[0, 1, 2, 3],[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int8)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int8)

***
### 1. Understanding strides
<mark>Question</mark> Determine the strides for the following arrays. Check your answer with `x.strides`.

In [3]:
# 1.1
y = x.reshape((2, 8))
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]], dtype=int8)

In [4]:
# 1.2
z = x.reshape((1, 16))
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]],
      dtype=int8)

In [5]:
# 1.3
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int16)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int16)

***
### 2. Metadata modification vs copying the data buffer

<mark>Question</mark> How do you explain the next result? Is it the same for `x.flatten()`?

In [22]:
x = np.random.rand(3, 3)
y = x.ravel()  #  flatten the array
y[0] = 100.
x

array([[100.        ,   0.71727624,   0.26728108],
       [  0.90846451,   0.12165977,   0.30565184],
       [  0.25427358,   0.89679246,   0.28147918]])

<mark>Question</mark> The next three cells do the same two operations: transposing a matrix and flattening it. How do you explain the difference in execution time?

In [6]:
x = np.random.rand(5000, 5000)

In [7]:
%%timeit
# 2.1
x.T
x.ravel()

423 ns ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
%%timeit
# 2.2
x.T.ravel()   #### ADD A FIGURE

72.9 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%%timeit
# 2.3
x.T
x.flatten()

29.7 ms ± 7.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


***
# 3. Broadcasting
The concept [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) has to do with the way NumPy treats the arrays during operations involving different shapes. For instance, an array of shape `(5,)` added to an escalar, gives an array of shape `(5, )` where to all the elements was added the escaler:

In [42]:
x = np.arange(5)   # of shape (5,)
x + 1.

array([1., 2., 3., 4., 5.])

An important operation in broadcasting is to create new dimensions of an array using `np.newaxis` .

In [7]:
x = np.arange(5)
x.shape

(5,)

In [11]:
x[:, np.newaxis].shape

(5, 1)

In [10]:
x[np.newaxis, :].shape

(1, 5)

<mark>Question</mark> From what you have already learned about the `numpy.ndarray`s, the operation `x[:, np.newaxis]` allocates new memory or can it be described with only a change on the metadata?

***

Broadcasting is often usefull to perform operations that are not vectorial in the mathematical sense, in a vectorial fashion. For instance, the next cell produces the array `y` with the different of all the possible combinations of the elements of `x`.

In [14]:
y = x[:, np.newaxis] + x[np.newaxis, :]
y.shape

(5, 5)

Here what happens is that each element of the `(5, 1)` array is added the `(5,)` element of the `(1, 5)` array. This will already know that produces an array of shape `(5,)`. Repeated for the five elements, this gives a `(5, 5)` array. 

***

Let's see know how to get again the difference of all combinations of the `(3,)` elements of a `(10, 3)` array:

In [40]:
x = np.random.rand(10, 3)
x.shape

(10, 3)

In [39]:
x[:, np.newaxis, :].shape

(10, 1, 3)

In [34]:
x[np.newaxis, :, :].shape

(1, 10, 3)

In [33]:
(x[np.newaxis, :, :] - x[:, np.newaxis, :]).shape

(10, 10, 3)