# Understanding the `numpy.ndarray` internals

In [2]:
import numpy as np

In [2]:
x = np.array([[0, 1, 2, 3],[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int8)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int8)

***
### 1. Understanding strides
<mark>Question</mark> Determine the strides for the following arrays. Check your answer with `x.strides`.

In [3]:
# 1.1
y = x.reshape((2, 8))
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]], dtype=int8)

In [4]:
# 1.2
z = x.reshape((1, 16))
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]],
      dtype=int8)

In [5]:
# 1.3
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int16)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int16)

***
### 2. Metadata modification vs copying the data buffer

<mark>Question</mark> How do you explain the next result? Is it the same for `x.flatten()`?

In [22]:
x = np.random.rand(3, 3)
y = x.ravel()  #  flatten the array
y[0] = 100.
x

array([[100.        ,   0.71727624,   0.26728108],
       [  0.90846451,   0.12165977,   0.30565184],
       [  0.25427358,   0.89679246,   0.28147918]])

<mark>Question</mark> The next three cells do the same two operations: transposing a matrix and flattening it. How do you explain the difference in execution time?

In [6]:
x = np.random.rand(5000, 5000)

In [7]:
%%timeit
# 2.1
x.T
x.ravel()

423 ns ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
%%timeit
# 2.2
x.T.ravel()   #### ADD A FIGURE

72.9 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%%timeit
# 2.3
x.T
x.flatten()

29.7 ms ± 7.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
